=== Drekorian/ffmap/trunk/ffmap/src/cz/muni/fi/pb138/ffmap/xml/ffmapSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    <xsd:include schemaLocation="tagsSchema.xsd"/>
    <xsd:include schemaLocation="productsSchema.xsd" />
    <xsd:simpleType name="latType">
        <xsd:restriction base="xsd:double">
            <xsd:minInclusive value="-90" />
            <xsd:maxInclusive value="90" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="lonType">
        <xsd:restriction base="xsd:double">
            <xsd:minInclusive value="-180" />
            <xsd:maxInclusive value="180" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="cityType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([a-žA-Ž])+" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="streetType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([a-žA-Ž])+" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="stNumType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[1-9]([0-9])*([A-Z])?" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="priceType">
        <xsd:restriction base="xsd:double">
            <xsd:minInclusive value="1" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="fastfood-database" type="ffDatabase">
        <xsd:key name="jointIDUnique">
            <xsd:selector xpath="joint" />
            <xsd:field xpath="@id" />
        </xsd:key>
        
    </xsd:element>

    <xsd:complexType name="ffDatabase">
        <xsd:sequence>
            <xsd:element name="joint" type="jointType" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="jointType">
        <xsd:sequence minOccurs="1">
            <xsd:element name="location" type="locationType" />
            <xsd:element name="opening-hours" type="hoursType" />
            <xsd:element name="menu" type="menuType" />
            <xsd:element name="tags" type="tagsType" />
            <xsd:element name="comments" type="commentsType" />
            <xsd:element name="web-page" type="xsd:anyURI" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:positiveInteger" use="required" />
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="locationType">
        <xsd:sequence minOccurs="1">
            <xsd:element name="adress" type="adressType" />
        </xsd:sequence>
        <xsd:attribute name="lat" type="latType" use="required" />
        <xsd:attribute name="lon" type="lonType" use="required" />
    </xsd:complexType>

    <xsd:complexType name="adressType">
        <xsd:sequence minOccurs="1">
            <xsd:element name="city" type="cityType" />
            <xsd:element name="street" type="streetType" />
            <xsd:element name="street-number" type="stNumType" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="hoursType">
        <xsd:sequence>
            <xsd:element name="mon" type="dayHoursType"/>
            <xsd:element name="tue" type="dayHoursType"/>
            <xsd:element name="wed" type="dayHoursType"/>
            <xsd:element name="thu" type="dayHoursType"/>
            <xsd:element name="fri" type="dayHoursType"/>
            <xsd:element name="sat" type="dayHoursType"/>
            <xsd:element name="sun" type="dayHoursType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="dayHoursType">
        <xsd:sequence>
            <xsd:element name="open-span" type="openSpanType" maxOccurs="2" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="openSpanType">
        <xsd:sequence minOccurs="1">
            <xsd:element name="start" type="xsd:time" />
            <xsd:element name="end" type="xsd:time" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="menuType">
        <xsd:sequence>
            <xsd:element name="menu-item" type="itemType" minOccurs="1" maxOccurs="unbounded">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="itemType">
        <xsd:sequence>
            <xsd:element name="product-ref" type="xsd:positiveInteger">
                <xsd:keyref name="productRef" refer="productUniqueID">
                    <xsd:selector xpath="product" />
                    <xsd:field xpath="@id" />
                </xsd:keyref>
            </xsd:element>
            <xsd:element name="price" type="priceType" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tagsType">
        <xsd:sequence minOccurs="1">
            <xsd:element name="tag" type="xsd:string" maxOccurs="unbounded" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="commentsType">
        <xsd:sequence minOccurs="0">
            <xsd:element name="comment" type="xsd:string" />
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== Drekorian/ffmap/trunk/ffmap/src/cz/muni/fi/pb138/ffmap/xml/ffmapSampleDatabase.xml
<?xml version="1.0" encoding="UTF-8"?>

<fastfood-database xsi:noNamespaceSchemaLocation="ffmapSchema.xsd" xmlns=""
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <joint id="1" name="Vyhlídal">
       <location lat="32.2222" lon="45.55555">
           <adress>
               <city>Brno</city>
               <street>Sladkého</street>
               <street-number>9A</street-number>
           </adress>
       </location>
       <opening-hours>
           <mon>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </mon>
           <tue>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </tue>
           <wed>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </wed>
           <thu>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </thu>
           <fri>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </fri>
           <sat>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </sat>
           <sun>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </sun>
       </opening-hours>
       <menu>
           <menu-item>
               <product-ref>1</product-ref>
               <price>10.00</price>
           </menu-item>
           <menu-item>
               <product-ref>3</product-ref>
               <price>27.00</price>
           </menu-item>
       </menu>
       <tags>
           <tag>Kentus</tag>
       </tags>
       <comments/>
       <web-page>http://www.stash.wz.cz</web-page>
   </joint>
</fastfood-database>

=== Drekorian/ffmap/trunk/ffmap/build/classes/cz/muni/fi/pb138/ffmap/xml/ffmapSampleDatabase.xml
<?xml version="1.0" encoding="UTF-8"?>

<fastfood-database xsi:noNamespaceSchemaLocation="ffmapSchema.xsd" xmlns=""
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <joints>
   <joint id="1" name="Vyhlídal">
       <location lat="32.2222" lon="45.55555">
           <adress>
               <city>Brno</city>
               <street>Sladkého</street>
               <street-number>9A</street-number>
           </adress>
       </location>
       <opening-hours>
           <mon>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </mon>
           <tue>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </tue>
           <wed>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </wed>
           <thu>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </thu>
           <fri>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </fri>
           <sat>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </sat>
           <sun>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </sun>
       </opening-hours>
       <menu>
           <menu-item product-ref="1">
               <price>10.00</price>
           </menu-item>
           <menu-item product-ref="3">
               <price>27.00</price>
           </menu-item>
       </menu>
       <tags>
           <tag>Kentus</tag>
       </tags>
       <comments/>
       <web-page>http://www.stash.wz.cz</web-page>
   </joint>
   <joint id="2" name="Nguyen Kong Noodles">
       <location lat="32.2222" lon="45.55555">
           <adress>
               <city>Brno</city>
               <street>Sladkého</street>
               <street-number>9A</street-number>
           </adress>
       </location>
       <opening-hours>
           <mon>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </mon>
           <tue>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </tue>
           <wed>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </wed>
           <thu>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </thu>
           <fri>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </fri>
           <sat>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </sat>
           <sun>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </sun>
       </opening-hours>
       <menu>
           <menu-item product-ref="1">
               <price>10.00</price>
           </menu-item>
           <menu-item product-ref="3">
               <price>27.00</price>
           </menu-item>
       </menu>
       <tags>
           <tag>Kentus</tag>
       </tags>
       <comments/>
       <web-page>http://www.stash.wz.cz</web-page>
   </joint>
   </joints>
   <products>
       <product id="1" name="Hermelínový hamburger" />
       <product id="2" name="Hot dog"/>
       <product id="3" name="Hnus fialovej">
           <description>Hnis</description>
       </product>
   </products>
</fastfood-database>

=== Drekorian/ffmap/trunk/ffmapWeb/src/java/cz/muni/fi/pb138/ffmap/xml/ffmapDatabase.xml
<?xml version="1.0" encoding="UTF-8"?>

<fastfood-database xsi:noNamespaceSchemaLocation="ffmapSchema.xsd" xmlns=""
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" joints-key-number="3" meals-key-number="6" users-key-number="2">
   <joints>
   <joint id="1" name="Bistro u Nováků" added-by="1">
       <location lat="49.20492" lon="16.59665">
           <adress>
               <city>Brno</city>
               <street-name>Kotlářská</street-name>
               <street-number>11</street-number>
           </adress>
       </location>
       <opening-hours>
           <mon>
                <open-span>
                    <start>08:00:00</start>
                    <end>20:00:00</end>
                </open-span>
           </mon>
           <tue>
                <open-span>
                    <start>08:00:00</start>
                    <end>20:00:00</end>
                </open-span>
           </tue>
           <wed>
                <open-span>
                    <start>08:00:00</start>
                    <end>20:00:00</end>
                </open-span>
           </wed>
           <thu>
                <open-span>
                    <start>08:00:00</start>
                    <end>20:00:00</end>
                </open-span>
           </thu>
           <fri>
                <open-span>
                    <start>08:00:00</start>
                    <end>20:00:00</end>
                </open-span>
           </fri>
           <sat>
                <open-span>
                    <start>08:00:00</start>
                    <end>20:00:00</end>
                </open-span>
           </sat>
           <sun>
                <open-span>
                    <start>08:00:00</start>
                    <end>20:00:00</end>
                </open-span>
           </sun>
       </opening-hours>
       <menu>
           <menu-item meal-ref="1">
               <price from="08:00:00" to="20:00:00">15.00</price>
           </menu-item>
           <menu-item meal-ref="2">
               <price from="00:00:00" to="20:00:00">16.00</price>
           </menu-item>
       </menu>
       <tags>
           <tag>hotdog</tag>
           <tag>kecup</tag>
           <tag>horcice</tag>
       </tags>
       <comments>
           <comment>chutnalo!</comment>
           <comment>mi ne!</comment>
       </comments>
       <web-page>http://www.novaci.cz</web-page>
   </joint>
   <joint id="2" name="Asia Bistro">
       <location lat="49.20285" lon="16.60446">
           <adress>
               <city>Brno</city>
               <street-name>Nádražní</street-name>
               <street-number>6</street-number>
           </adress>
       </location>
       <opening-hours>
           <mon>
                <open-span>
                    <start>09:00:00</start>
                    <end>23:00:00</end>
                </open-span>
           </mon>
           <tue>
                <open-span>
                    <start>09:00:00</start>
                    <end>23:00:00</end>
                </open-span>
           </tue>
           <wed>
                <open-span>
                    <start>09:00:00</start>
                    <end>23:00:00</end>
                </open-span>
           </wed>
           <thu>
                <open-span>
                    <start>09:00:00</start>
                    <end>23:00:00</end>
                </open-span>
           </thu>
           <fri>
                <open-span>
                    <start>09:00:00</start>
                    <end>23:00:00</end>
                </open-span>
           </fri>
           <sat>
                <open-span>
                    <start>09:00:00</start>
                    <end>23:00:00</end>
                </open-span>
           </sat>
           <sun>
                <open-span>
                    <start>09:00:00</start>
                    <end>23:00:00</end>
                </open-span>
           </sun>
       </opening-hours>
       <menu>
           <menu-item meal-ref="3">
               <price from="00:00:00" to="23:59:59">42.00</price>
           </menu-item>
           <menu-item meal-ref="4">
               <price from="00:00:00" to="23:59:59">41.00</price>
           </menu-item>
           <menu-item meal-ref="6">
               <price from="00:00:00" to="23:59:59">55.00</price>
           </menu-item>
       </menu>
       <tags>
           <tag>hamburger</tag>
           <tag>cheeseburger</tag>
           <tag>kebab</tag>
       </tags>
       <comments/>
       <web-page>http://www.asia.cz</web-page>
   </joint>
   <joint id="3" name="Dragon">
       <location lat="49.201672" lon="16.610641">
           <adress>
               <city>Brno</city>
               <street-name>Masarykova</street-name>
               <street-number>135</street-number>
           </adress>
       </location>
       <opening-hours>
           <mon>
                <open-span>
                    <start>12:00:00</start>
                    <end>18:00:00</end>
                </open-span>
           </mon>
           <tue>
                <open-span>
                    <start>12:00:00</start>
                    <end>18:00:00</end>
                </open-span>
           </tue>
           <wed>
                <open-span>
                    <start>12:00:00</start>
                    <end>18:00:00</end>
                </open-span>
           </wed>
           <thu>
                <open-span>
                    <start>12:00:00</start>
                    <end>18:00:00</end>
                </open-span>
           </thu>
           <fri>
                <open-span>
                    <start>12:00:00</start>
                    <end>18:00:00</end>
                </open-span>
           </fri>
           <sat>
                <open-span>
                    <start>12:00:00</start>
                    <end>18:00:00</end>
                </open-span>
           </sat>
           <sun>
                <open-span>
                    <start>12:00:00</start>
                    <end>18:00:00</end>
                </open-span>
           </sun>
       </opening-hours>
       <menu>
           <menu-item meal-ref="4">
               <price from="12:00:00" to="18:00:00">39.00</price>
           </menu-item>
           <menu-item meal-ref="5">
               <price from="12:00:00" to="18:00:00">39.00</price>
           </menu-item>
           <menu-item meal-ref="6">
               <price from="00:00:00" to="18:00:00">49.00</price>
           </menu-item>
       </menu>
       <tags>
           <tag>cheeseburger</tag>
           <tag>kebab</tag>
       </tags>
       <comments/>
       <web-page>http://www.dragon.eu</web-page>
   </joint>
   </joints>
   <meals>
       <meal id="1" name="Párek v rohlíku s kečupem" />
       <meal id="2" name="Párek v rohlíku s hořčicí"/>
       <meal id="3" name="Hamburger"/>
       <meal id="4" name="Cheeseburger"/>
       <meal id="5" name="Hamburger s kebabem"/>
       <meal id="6" name="Hamburger se smaženým sýrem">
           <description>Hamburger s masem a smaženým sýrem</description>
       </meal>
   </meals>
   <users>
       <user id="1">
           <username>admin</username>
           <password>d033e22ae348aeb5660fc2140aec35850c4da997</password>
           <role>admin</role>
           <first-name>Marek</first-name>
           <surname>Osvald</surname>
           <date-registered>2011-06-12</date-registered>
           <active>true</active>
       </user>
       <user id="2">
           <username>admin2</username>
           <password>d033e22ae348aeb5660fc2140aec35850c4da997</password>
           <role>admin</role>
           <first-name>Aleksandar</first-name>
           <surname>Zivkovic</surname>
           <date-registered>2011-06-12</date-registered>
           <active>true</active>
       </user>
   </users>
</fastfood-database>
