=== Drekorian/ffmap/ffmapWeb/src/java/cz/muni/fi/pb138/ffmap/xml/ffMapSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    <xsd:simpleType name="latType">
        <xsd:restriction base="xsd:decimal">
            <xsd:minInclusive value="-90" />
            <xsd:maxInclusive value="90" />
            <xsd:fractionDigits value="6"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="lonType">
        <xsd:restriction base="xsd:decimal">
            <xsd:minInclusive value="-180" />
            <xsd:maxInclusive value="180" />
            <xsd:fractionDigits value="6"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="cityType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([a-žA-Ž])+" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="streetType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([a-žA-Ž])+" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="stNumType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[1-9]([0-9])*([A-Z])?" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="priceValueType">
        <xsd:restriction base="xsd:decimal">
            <xsd:minInclusive value="1" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="userNameType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([a-zA-Z0-9])+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="passwordType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([a-zA-Z0-9])+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="nameType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([a-žA-Ž])+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="roleType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="user"/>
            <xsd:enumeration value="admin"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="fastfood-database" type="ffDatabase">
        <xsd:key name="jointIDUnique">
            <xsd:selector xpath="joints/joint" />
            <xsd:field xpath="@id" />
        </xsd:key>
        <xsd:key name="mealUniqueID">
            <xsd:selector xpath="meals/meal" />
            <xsd:field xpath="@id" />
        </xsd:key>
        <xsd:keyref name="mealRef" refer="mealUniqueID">
                    <xsd:selector xpath="joints/joint/menu/menu-item" />
                    <xsd:field xpath="@meal-ref" />
        </xsd:keyref>
        <xsd:keyref name="userRef" refer="userIDUnique">
            <xsd:selector xpath="joints/joint"/>
            <xsd:field xpath="@added-by"/>
        </xsd:keyref>
        <xsd:key name="userIDUnique">
            <xsd:selector xpath="users/user"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
    </xsd:element>

    <xsd:complexType name="ffDatabase">
        <xsd:sequence>
            <xsd:element name="joints" type="jointsType" minOccurs="1" maxOccurs="1" />
            <xsd:element name="meals" type="mealsType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="users" type="usersType" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="joints-key-number" type="xsd:positiveInteger" use="required" />
        <xsd:attribute name="meals-key-number" type="xsd:positiveInteger" use="required" />
        <xsd:attribute name="users-key-number" type="xsd:positiveInteger" use="required" />
    </xsd:complexType>

    <xsd:complexType name="jointsType">
        <xsd:sequence>
            <xsd:element name="joint" type="jointType" minOccurs="0" maxOccurs="unbounded">
                <xsd:unique name="refUnique">
                    <xsd:selector xpath="menu/menu-item"/>
                    <xsd:field xpath="@meal-ref"/>
                </xsd:unique>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="jointType">
        <xsd:sequence minOccurs="1">
            <xsd:element name="location" type="locationType" />
            <xsd:element name="opening-hours" type="hoursType" />
            <xsd:element name="menu" type="menuType" />
            <xsd:element name="tags" type="tagsType" />
            <xsd:element name="comments" type="commentsType" />
            <xsd:element name="web-page" type="xsd:anyURI" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:positiveInteger" use="required" />
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="added-by" type="xsd:positiveInteger"/>
    </xsd:complexType>

    <xsd:complexType name="locationType">
        <xsd:sequence minOccurs="1">
            <xsd:element name="adress" type="adressType" />
        </xsd:sequence>
        <xsd:attribute name="lat" type="latType" use="required" />
        <xsd:attribute name="lon" type="lonType" use="required" />
    </xsd:complexType>

    <xsd:complexType name="adressType">
        <xsd:sequence minOccurs="1">
            <xsd:element name="city" type="cityType" />
            <xsd:element name="street-name" type="streetType" />
            <xsd:element name="street-number" type="stNumType" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="hoursType">
        <xsd:sequence>
            <xsd:element name="mon" type="dayHoursType"/>
            <xsd:element name="tue" type="dayHoursType"/>
            <xsd:element name="wed" type="dayHoursType"/>
            <xsd:element name="thu" type="dayHoursType"/>
            <xsd:element name="fri" type="dayHoursType"/>
            <xsd:element name="sat" type="dayHoursType"/>
            <xsd:element name="sun" type="dayHoursType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="dayHoursType">
        <xsd:sequence>
            <xsd:element name="open-span" type="openSpanType" minOccurs="1" maxOccurs="2" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="openSpanType">
        <xsd:sequence minOccurs="1">
            <xsd:element name="start" type="xsd:time" />
            <xsd:element name="end" type="xsd:time" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="menuType">
        <xsd:sequence>
            <xsd:element name="menu-item" type="itemType" minOccurs="1" maxOccurs="unbounded">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="itemType">
        <xsd:sequence>
            <xsd:element name="price" type="priceType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="meal-ref" type="xsd:positiveInteger" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="priceType">
        <xsd:simpleContent>
            <xsd:extension base="priceValueType">
                <xsd:attribute name="from" type="xsd:time" use="optional" default="00:00:00"/>
                <xsd:attribute name="to" type="xsd:time" use="optional" default="23:59:59"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="tagsType">
        <xsd:sequence minOccurs="1">
            <xsd:element name="tag" type="xsd:string" maxOccurs="unbounded" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="commentsType">
        <xsd:sequence>
            <xsd:element name="comment" type="xsd:string" maxOccurs="unbounded" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="mealsType">
        <xsd:sequence>
            <xsd:element name="meal" type="mealType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="mealType">
        <xsd:all minOccurs="0">
            <xsd:element name="description" type="xsd:string" />
        </xsd:all>
        <xsd:attribute name="id" type="xsd:positiveInteger" use="required" />
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="usersType">
        <xsd:sequence>
            <xsd:element name="user" type="userType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="userType">
        <xsd:sequence>
            <xsd:element name="username" type="userNameType"/>
            <xsd:element name="password" type="passwordType"/>
            <xsd:element name="role" type="roleType"/>
            <xsd:element name="first-name" type="nameType"/>
            <xsd:element name="surname" type="nameType"/>
            <xsd:element name="date-registered" type="xsd:date"/>
            <xsd:element name="active" type="xsd:boolean" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:positiveInteger" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== Drekorian/ffmap/ffmapWeb/xml_data/ffmapDatabase.xml
<?xml version="1.0" encoding="UTF-8"?>

<fastfood-database xsi:noNamespaceSchemaLocation="ffmapSchema.xsd" xmlns=""
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" joints-key-number="2" meals-key-number="3" users-key-number="1">
   <joints>
   <joint id="1" name="Vyhlídal" added-by="1">
       <location lat="32.2222" lon="45.55555">
           <adress>
               <city>Brno</city>
               <street-name>Sladkého</street-name>
               <street-number>9A</street-number>
           </adress>
       </location>
       <opening-hours>
           <mon>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </mon>
           <tue>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </tue>
           <wed>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </wed>
           <thu>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </thu>
           <fri>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </fri>
           <sat>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </sat>
           <sun>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </sun>
       </opening-hours>
       <menu>
           <menu-item meal-ref="1">
               <price from="10:00:00" to="20:00:00">10.00</price>
           </menu-item>
           <menu-item meal-ref="3">
               <price from="00:00:00" to="23:59:59">27.00</price>
           </menu-item>
       </menu>
       <tags>
           <tag>Kentus</tag>
       </tags>
       <comments/>
       <web-page>http://www.stash.wz.cz</web-page>
   </joint>
   <joint id="2" name="Nguyen Kong Noodles">
       <location lat="32.2222" lon="45.55555">
           <adress>
               <city>Brno</city>
               <street-name>Sladkého</street-name>
               <street-number>9A</street-number>
           </adress>
       </location>
       <opening-hours>
           <mon>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </mon>
           <tue>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </tue>
           <wed>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </wed>
           <thu>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </thu>
           <fri>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </fri>
           <sat>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </sat>
           <sun>
                <open-span>
                    <start>08:00:00</start>
                    <end>23:30:00</end>
                </open-span>
           </sun>
       </opening-hours>
       <menu>
           <menu-item meal-ref="1">
               <price from="00:00:00" to="23:59:59">10.00</price>
           </menu-item>
           <menu-item meal-ref="3">
               <price from="00:00:00" to="23:59:59">27.00</price>
           </menu-item>
       </menu>
       <tags>
           <tag>Kentus</tag>
       </tags>
       <comments/>
       <web-page>http://www.stash.wz.cz</web-page>
   </joint>
   </joints>
   <meals>
       <meal id="1" name="Hermelínový hamburger" />
       <meal id="2" name="Hot dog"/>
       <meal id="3" name="Hnus fialovej">
           <description>Hnis</description>
       </meal>
   </meals>
   <users>
       <user id="1">
           <username>admin</username>
           <password>d033e22ae348aeb5660fc2140aec35850c4da997</password> <!--SHA1 of "admin"-->
           <role>admin</role>
           <first-name>Jan</first-name>
           <surname>Sourek</surname>
           <date-registered>2011-06-12</date-registered>
           <active>true</active>
       </user>
   </users>
</fastfood-database>
